services:
    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: paylist
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres -d paylist']
            interval: 5s
            timeout: 5s
            retries: 10

    redis:
        image: redis:8
        command: redis-server --appendonly yes --appendfsync everysec
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 5s
            retries: 5

    # client:
    #     build:
    #         context: www-client
    #         dockerfile: Dockerfile
    #     ports:
    #         - '5173:5173'
    #     volumes:
    #         - ./www-client:/app
    #         - /app/node_modules
    #     depends_on:
    #         - db
    #         - redis

    http_server:
        restart: always
        build:
            context: http-server
            dockerfile: Dockerfile
        env_file: './http-server/.env.docker'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            DB_ADDR: postgres://postgres:password@host.docker.internal:5432/paylist?sslmode=disable
        volumes:
            - ./http-server:/app
        command: air
        ports:
            - '8080:8080'
        depends_on:
            redis:
                condition: service_healthy

volumes:
    redis_data:
