export const QUERY_KEYS = {
	userLoginState: 'respUserLoginState',
	userSettings: 'respUserSettings',
	userReferral: 'respUserReferral',
	trackedSubscriptionList: 'respTrackedSubscriptionList',
	trackedSubscriptionSummary: 'respTrackedSubscriptionSummary',
	trackedSubscriptionDetail: 'respTrackedSubscriptionDetail',
	trackedSubscriptionCategoryList: 'respTrackedSubscriptionCategoryList',
	trackedSubscriptionMembers: 'respTrackedSubscriptionMembers',
	currencyRates: 'respCurrencyRates',
	countryList: 'respCountryList',
	adminRecipients: 'respAdminRecipients',
	planList: 'respPlanList',
	paymentBilling: 'respPaymentBilling',
	trackedSubscriptionAnalytics: 'respTrackedSubscriptionAnalytics',
} as const;
