-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS user_cores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    user_uuid VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    email_confirmed BOOLEAN DEFAULT FALSE,
    avatars TEXT,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    password VARCHAR(255) NOT NULL CHECK (char_length(password) > 5),
    is_admin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_user_cores_email ON user_cores(email);
CREATE INDEX IF NOT EXISTS idx_user_cores_user_uuid ON user_cores(user_uuid);

CREATE OR REPLACE FUNCTION set_updated_at_user_cores()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_updated_at_user_cores_trigger ON user_cores;
CREATE TRIGGER set_updated_at_user_cores_trigger
    BEFORE UPDATE ON user_cores
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_user_cores();

CREATE TABLE IF NOT EXISTS user_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    user_uuid VARCHAR(255) NOT NULL UNIQUE REFERENCES user_cores(user_uuid) ON DELETE CASCADE,

    plan_name TEXT NOT NULL DEFAULT 'Free',
    valid_from TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    valid_to TIMESTAMPTZ,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    auto_renew_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    yookassa_payment_method_id TEXT,
    payment_method_type TEXT,
    payment_method_title TEXT,
    payment_method_saved_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_user_subscriptions_user_uuid ON user_subscriptions(user_uuid);
CREATE INDEX IF NOT EXISTS idx_user_subscriptions_plan_name ON user_subscriptions(plan_name);
CREATE INDEX IF NOT EXISTS idx_user_cores_is_admin ON user_cores(is_admin) WHERE is_admin = TRUE;

CREATE OR REPLACE FUNCTION set_updated_at_user_subscriptions()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_updated_at_user_subscriptions_trigger ON user_subscriptions;
CREATE TRIGGER set_updated_at_user_subscriptions_trigger
    BEFORE UPDATE ON user_subscriptions
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_user_subscriptions();

COMMENT ON TABLE user_subscriptions IS 'Active SaaS subscription of a user in Paylist';
COMMENT ON COLUMN user_cores.is_admin IS 'Operator account that can send broadcast messages';
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS set_updated_at_user_subscriptions_trigger ON user_subscriptions;
DROP FUNCTION IF EXISTS set_updated_at_user_subscriptions();
DROP INDEX IF EXISTS idx_user_subscriptions_plan_name;
DROP INDEX IF EXISTS idx_user_subscriptions_user_uuid;
DROP TABLE IF EXISTS user_subscriptions;

DROP TRIGGER IF EXISTS set_updated_at_user_cores_trigger ON user_cores;
DROP FUNCTION IF EXISTS set_updated_at_user_cores();
DROP INDEX IF EXISTS idx_user_cores_user_uuid;
DROP INDEX IF EXISTS idx_user_cores_email;
DROP TABLE IF EXISTS user_cores;
-- +goose StatementEnd
