-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS payment_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),

    user_uuid VARCHAR(255) NOT NULL REFERENCES user_cores(user_uuid) ON DELETE CASCADE,
    plan_name TEXT NOT NULL REFERENCES subscriptions(plan_name) ON UPDATE CASCADE ON DELETE RESTRICT,

    yookassa_payment_id TEXT NOT NULL,
    yookassa_payment_method_id TEXT,

    amount DECIMAL(10, 2) NOT NULL DEFAULT 0,
    currency TEXT NOT NULL DEFAULT 'RUB',

    -- pending | waiting_for_capture | succeeded | canceled | failed
    status TEXT NOT NULL DEFAULT 'pending',
    -- initial | renewal | manual
    payment_kind TEXT NOT NULL DEFAULT 'initial',

    description TEXT,
    paid_at TIMESTAMPTZ,
    metadata JSONB,

    CONSTRAINT uq_payment_history_yookassa_payment_id UNIQUE (yookassa_payment_id)
);

CREATE INDEX IF NOT EXISTS idx_user_subscriptions_auto_renew
    ON user_subscriptions(auto_renew_enabled)
    WHERE auto_renew_enabled = TRUE;

CREATE INDEX IF NOT EXISTS idx_user_subscriptions_yookassa_payment_method_id
    ON user_subscriptions(yookassa_payment_method_id)
    WHERE yookassa_payment_method_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_payment_history_user_uuid ON payment_history(user_uuid);
CREATE INDEX IF NOT EXISTS idx_payment_history_plan_name ON payment_history(plan_name);
CREATE INDEX IF NOT EXISTS idx_payment_history_status ON payment_history(status);
CREATE INDEX IF NOT EXISTS idx_payment_history_user_uuid_status ON payment_history(user_uuid, status);
CREATE INDEX IF NOT EXISTS idx_payment_history_created_at ON payment_history(created_at DESC);

CREATE OR REPLACE FUNCTION set_updated_at_payment_history()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_updated_at_payment_history_trigger ON payment_history;
CREATE TRIGGER set_updated_at_payment_history_trigger
    BEFORE UPDATE ON payment_history
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_payment_history();

COMMENT ON TABLE payment_history IS 'History of YooKassa payments for Paylist SaaS subscriptions';
COMMENT ON COLUMN payment_history.id IS 'Primary key of the payment record';
COMMENT ON COLUMN payment_history.created_at IS 'Payment record creation timestamp (UTC)';
COMMENT ON COLUMN payment_history.updated_at IS 'Payment record last update timestamp (UTC)';
COMMENT ON COLUMN payment_history.user_uuid IS 'User who initiated the payment; cascades on user deletion';
COMMENT ON COLUMN payment_history.plan_name IS 'Tariff plan name at the time of payment';
COMMENT ON COLUMN payment_history.yookassa_payment_id IS 'Unique payment identifier from YooKassa';
COMMENT ON COLUMN payment_history.yookassa_payment_method_id IS 'Saved YooKassa payment method ID for recurring charges';
COMMENT ON COLUMN payment_history.amount IS 'Payment amount charged';
COMMENT ON COLUMN payment_history.currency IS 'ISO currency code for the payment amount';
COMMENT ON COLUMN payment_history.status IS 'Payment status: pending, waiting_for_capture, succeeded, canceled, failed';
COMMENT ON COLUMN payment_history.payment_kind IS 'Payment type: initial, renewal, manual';
COMMENT ON COLUMN payment_history.description IS 'Optional payment description shown to the user';
COMMENT ON COLUMN payment_history.paid_at IS 'Timestamp when the payment was successfully completed (UTC)';
COMMENT ON COLUMN payment_history.metadata IS 'Additional payment metadata from YooKassa or internal processing (JSONB)';
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP INDEX IF EXISTS idx_user_subscriptions_yookassa_payment_method_id;
DROP INDEX IF EXISTS idx_user_subscriptions_auto_renew;

DROP INDEX IF EXISTS idx_payment_history_user_uuid_status;
DROP INDEX IF EXISTS idx_payment_history_plan_name;
DROP INDEX IF EXISTS idx_payment_history_user_uuid;
DROP INDEX IF EXISTS idx_payment_history_status;
DROP INDEX IF EXISTS idx_payment_history_created_at;

DROP TRIGGER IF EXISTS set_updated_at_payment_history_trigger ON payment_history;
DROP FUNCTION IF EXISTS set_updated_at_payment_history();

DROP TABLE IF EXISTS payment_history;
-- +goose StatementEnd
