-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS user_referrals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    referrer_uuid VARCHAR(255) NOT NULL REFERENCES user_cores(user_uuid) ON DELETE CASCADE,
    referred_uuid VARCHAR(255) NOT NULL UNIQUE REFERENCES user_cores(user_uuid) ON DELETE CASCADE,
    converted_at TIMESTAMPTZ,
    CONSTRAINT user_referrals_no_self CHECK (referrer_uuid <> referred_uuid)
);

CREATE INDEX IF NOT EXISTS idx_user_referrals_referrer_uuid ON user_referrals (referrer_uuid);
CREATE INDEX IF NOT EXISTS idx_user_referrals_converted ON user_referrals (referrer_uuid, converted_at)
    WHERE converted_at IS NOT NULL;

CREATE TABLE IF NOT EXISTS user_referral_rewards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    user_uuid VARCHAR(255) NOT NULL REFERENCES user_cores(user_uuid) ON DELETE CASCADE,
    rank INTEGER NOT NULL,
    days_granted INTEGER NOT NULL,
    UNIQUE (user_uuid, rank)
);

COMMENT ON TABLE user_referrals IS 'Invited users; converted_at is set after the invitee pays any Paylist plan';
COMMENT ON TABLE user_referral_rewards IS 'One-time premium grants for referral rank thresholds';
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS user_referral_rewards;
DROP TABLE IF EXISTS user_referrals;
-- +goose StatementEnd
