-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS tracked_subscription_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),

    tracked_subscription_id BIGINT NOT NULL REFERENCES tracked_subscriptions(id) ON DELETE CASCADE,
    user_uuid VARCHAR(255) REFERENCES user_cores(user_uuid) ON DELETE CASCADE,
    email VARCHAR(255) NOT NULL,

    role VARCHAR(16) NOT NULL DEFAULT 'member',
    share_percent NUMERIC(6, 3) NOT NULL,
    notification BOOLEAN NOT NULL DEFAULT FALSE,
    include_in_analytics BOOLEAN NOT NULL DEFAULT TRUE,
    status VARCHAR(16) NOT NULL DEFAULT 'pending',

    note TEXT,
    invite_token VARCHAR(64),
    invite_expires_at TIMESTAMPTZ,

    CONSTRAINT chk_tracked_subscription_members_role CHECK (role IN ('owner', 'member')),
    CONSTRAINT chk_tracked_subscription_members_status CHECK (status IN ('pending', 'accepted', 'declined')),
    CONSTRAINT chk_tracked_subscription_members_share CHECK (share_percent >= 0 AND share_percent <= 100),
    CONSTRAINT uq_tracked_subscription_members_email UNIQUE (tracked_subscription_id, email)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tracked_subscription_members_invite_token
    ON tracked_subscription_members(invite_token)
    WHERE invite_token IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_tracked_subscription_members_user
    ON tracked_subscription_members(tracked_subscription_id, user_uuid)
    WHERE user_uuid IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_tracked_subscription_members_user_uuid ON tracked_subscription_members(user_uuid);
CREATE INDEX IF NOT EXISTS idx_tracked_subscription_members_email ON tracked_subscription_members(email);
CREATE INDEX IF NOT EXISTS idx_tracked_subscription_members_subscription_id ON tracked_subscription_members(tracked_subscription_id);

CREATE OR REPLACE FUNCTION set_tracked_subscription_members_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('UTC', now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_tracked_subscription_members_updated_at_trigger ON tracked_subscription_members;
CREATE TRIGGER set_tracked_subscription_members_updated_at_trigger
    BEFORE UPDATE ON tracked_subscription_members
    FOR EACH ROW
    EXECUTE FUNCTION set_tracked_subscription_members_updated_at();

COMMENT ON TABLE tracked_subscription_members IS 'Shared subscription members, pending invites and per-user notification/analytics flags. Free: max 2 members (owner + 1). Premium: unlimited members.';
COMMENT ON COLUMN tracked_subscription_members.share_percent IS 'Member share of the subscription price in percent';
COMMENT ON COLUMN tracked_subscription_members.notification IS 'Whether this member wants payment reminders';
COMMENT ON COLUMN tracked_subscription_members.include_in_analytics IS 'Whether this member includes the share in personal analytics';
COMMENT ON COLUMN tracked_subscription_members.note IS 'Personal note of this member for the shared subscription';
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS set_tracked_subscription_members_updated_at_trigger ON tracked_subscription_members;
DROP FUNCTION IF EXISTS set_tracked_subscription_members_updated_at();
DROP INDEX IF EXISTS idx_tracked_subscription_members_subscription_id;
DROP INDEX IF EXISTS idx_tracked_subscription_members_email;
DROP INDEX IF EXISTS idx_tracked_subscription_members_user_uuid;
DROP INDEX IF EXISTS uq_tracked_subscription_members_user;
DROP INDEX IF EXISTS uq_tracked_subscription_members_invite_token;
DROP TABLE IF EXISTS tracked_subscription_members;
-- +goose StatementEnd
