-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS tracked_subscription_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),

    tracked_subscription_id BIGINT NOT NULL REFERENCES tracked_subscriptions(id) ON DELETE CASCADE,
    user_uuid VARCHAR(255) NOT NULL REFERENCES user_cores(user_uuid) ON DELETE CASCADE,

    event_type VARCHAR(32) NOT NULL,
    previous_date_pay DATE,
    new_date_pay DATE NOT NULL,
    price NUMERIC(10, 3) NOT NULL,
    currency CHAR(3) NOT NULL,

    CONSTRAINT chk_tracked_subscription_history_event_type CHECK (event_type IN ('created', 'date_changed', 'renewed')),
    CONSTRAINT chk_tracked_subscription_history_currency CHECK (currency ~ '^[A-Z]{3}$')
);

CREATE INDEX IF NOT EXISTS idx_tracked_subscription_history_subscription_id ON tracked_subscription_history(tracked_subscription_id);
CREATE INDEX IF NOT EXISTS idx_tracked_subscription_history_user_uuid ON tracked_subscription_history(user_uuid);
CREATE INDEX IF NOT EXISTS idx_tracked_subscription_history_created_at ON tracked_subscription_history(created_at DESC);

COMMENT ON TABLE tracked_subscription_history IS 'History of tracked subscription payment date changes';
COMMENT ON COLUMN tracked_subscription_history.event_type IS 'created | date_changed | renewed';
COMMENT ON COLUMN tracked_subscription_history.previous_date_pay IS 'Previous next payment date (NULL on create)';
COMMENT ON COLUMN tracked_subscription_history.new_date_pay IS 'New next payment date after the event';
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP INDEX IF EXISTS idx_tracked_subscription_history_created_at;
DROP INDEX IF EXISTS idx_tracked_subscription_history_user_uuid;
DROP INDEX IF EXISTS idx_tracked_subscription_history_subscription_id;

DROP TABLE IF EXISTS tracked_subscription_history;
-- +goose StatementEnd
