-- +goose Up
-- +goose StatementBegin
UPDATE services SET aliases = ARRAY['нетфликс', 'netflix.com', 'netflix premium', 'netflix standard', 'netflix basic', 'нетфликс премиум'] WHERE slug = 'netflix';
UPDATE services SET aliases = ARRAY['prime video', 'amazon prime', 'amazon video', 'прайм видео', 'амазон прайм', 'prime', 'amazon prime video', 'прайм', 'prime amazon'] WHERE slug = 'prime-video';
UPDATE services SET aliases = ARRAY['disney plus', 'disney+', 'дисней', 'дисней плюс', 'disney', 'disneyplus', 'дисней+'] WHERE slug = 'disney-plus';
UPDATE services SET aliases = ARRAY['hbo', 'hbo max', 'hbo-max', 'мах', 'хбо', 'max streaming', 'hbomax', 'хбо макс'] WHERE slug = 'max';
UPDATE services SET aliases = ARRAY['хулу', 'hulu+', 'hulu plus', 'хулу плюс'] WHERE slug = 'hulu';
UPDATE services SET aliases = ARRAY['apple tv', 'apple tv plus', 'эппл тв', 'appletv', 'apple tv+', 'эпл тв', 'appletv+'] WHERE slug = 'apple-tv-plus';
UPDATE services SET aliases = ARRAY['paramount plus', 'paramount', 'парамаунт', 'paramount+', 'paramountplus', 'парамаунт плюс'] WHERE slug = 'paramount-plus';
UPDATE services SET aliases = ARRAY['peacock tv', 'peacock premium', 'peacock+'] WHERE slug = 'peacock';
UPDATE services SET aliases = ARRAY['discovery plus', 'discovery', 'дискавери', 'discovery+', 'discoveryplus', 'дискавери плюс'] WHERE slug = 'discovery-plus';
UPDATE services SET aliases = ARRAY['youtube premium', 'yt premium', 'ютуб', 'ютуб премиум', 'yt', 'youtube family'] WHERE slug = 'youtube';
UPDATE services SET aliases = ARRAY['youtube tv', 'ютуб тв', 'youtubetv'] WHERE slug = 'youtube-tv';
UPDATE services SET aliases = ARRAY['crunchy roll', 'кранчиролл', 'crunchyroll premium', 'crunchyroll mega fan', 'кранчи ролл'] WHERE slug = 'crunchyroll';
UPDATE services SET aliases = ARRAY['дазн', 'dazn plus'] WHERE slug = 'dazn';
UPDATE services SET aliases = ARRAY['espn plus', 'espn', 'espn+', 'espnplus'] WHERE slug = 'espn-plus';
UPDATE services SET aliases = ARRAY['fubotv', 'fubo tv', 'fubo.tv'] WHERE slug = 'fubo';
UPDATE services SET aliases = ARRAY['sling', 'slingtv', 'sling orange', 'sling blue'] WHERE slug = 'sling-tv';
UPDATE services SET aliases = ARRAY['now tv', 'nowtv'] WHERE slug = 'now-tv';
UPDATE services SET aliases = ARRAY['rakuten viki', 'viki rakuten', 'viki', 'вики'] WHERE slug = 'rakuten-viki';
UPDATE services SET aliases = ARRAY['муби', 'mubi.com'] WHERE slug = 'mubi';
UPDATE services SET aliases = ARRAY['shudder amc', 'шаддер'] WHERE slug = 'shudder';
UPDATE services SET aliases = ARRAY['curiositystream', 'curiosity', 'кьюриосити'] WHERE slug = 'curiosity-stream';
UPDATE services SET aliases = ARRAY['nebula.tv', 'небула'] WHERE slug = 'nebula';
UPDATE services SET aliases = ARRAY['патреон', 'patreon.com'] WHERE slug = 'patreon';
UPDATE services SET aliases = ARRAY['twitch turbo', 'твич', 'твич турбо', 'twitch.tv'] WHERE slug = 'twitch';
UPDATE services SET aliases = ARRAY['kinopoisk', 'кинопоиск hd', 'yandex kinopoisk', 'кинопоиск', 'kinopoisk hd', 'яндекс кинопоиск'] WHERE slug = 'kinopoisk';
UPDATE services SET aliases = ARRAY['ivi.ru', 'иви', 'ivi', 'иви.ру', 'ivi премиум'] WHERE slug = 'ivi';
UPDATE services SET aliases = ARRAY['окко', 'okko.tv', 'окко.тв', 'okko премиум'] WHERE slug = 'okko';
UPDATE services SET aliases = ARRAY['премьер', 'tnt premier', 'premier one', 'руспремьер'] WHERE slug = 'premier';
UPDATE services SET aliases = ARRAY['старт', 'start.ru', 'старт.ру', 'start ru'] WHERE slug = 'start';
UPDATE services SET aliases = ARRAY['винк', 'wink.ru', 'ростелеком wink', 'wink music', 'ростелеком винк'] WHERE slug = 'wink';
UPDATE services SET aliases = ARRAY['moretv', 'more tv', 'мор тв', 'more.tv', 'мор.тв'] WHERE slug = 'more-tv';
UPDATE services SET aliases = ARRAY['amedia', 'амедиатека', 'amediateka', 'амедиа'] WHERE slug = 'amediateka';
UPDATE services SET aliases = ARRAY['мегого', 'megogo.net'] WHERE slug = 'megogo';
UPDATE services SET aliases = ARRAY['кион', 'мтс кион', 'mts kion', 'мтс kion'] WHERE slug = 'kion';
UPDATE services SET aliases = ARRAY['viasat', 'viju tv', 'вижу', 'viju.ru'] WHERE slug = 'viju';
UPDATE services SET aliases = ARRAY['tv plus', 'тв плюс', 'tv+', 'тв+', 'tvplus'] WHERE slug = 'tvplus';
UPDATE services SET aliases = ARRAY['premier video', 'премьер видео'] WHERE slug = 'premier-video';
UPDATE services SET aliases = ARRAY['yandex plus', 'яндекс плюс', 'ya plus', 'plus.yandex', 'yandex premium', 'yandex pl', 'yandexplus', 'яндекс+', 'яндексплюс', 'яндекс премиум', 'яндекс подписка', 'yplus'] WHERE slug = 'yandex-plus';
UPDATE services SET aliases = ARRAY['вк видео', 'vk play video', 'vk video', 'вк плей видео'] WHERE slug = 'vk-video';
UPDATE services SET aliases = ARRAY['рутуб', 'rutube premium', 'rutube.ru'] WHERE slug = 'rutube';
UPDATE services SET aliases = ARRAY['шоуджет', 'show jet'] WHERE slug = 'showjet';
UPDATE services SET aliases = ARRAY['premier sport', 'премьер спорт'] WHERE slug = 'premier-sport';
UPDATE services SET aliases = ARRAY['match premier', 'матч премьер', 'match tv', 'матч тв'] WHERE slug = 'match-premier';
UPDATE services SET aliases = ARRAY['спотифай', 'spotify premium', 'spotify family', 'spotify duo'] WHERE slug = 'spotify';
UPDATE services SET aliases = ARRAY['apple music', 'эппл мьюзик', 'applemusic', 'эпл музыка', 'эппл музыка'] WHERE slug = 'apple-music';
UPDATE services SET aliases = ARRAY['yt music', 'ютуб музыка', 'youtube music', 'youtubemusic'] WHERE slug = 'youtube-music';
UPDATE services SET aliases = ARRAY['amazon music unlimited', 'prime music', 'амазон музыка'] WHERE slug = 'amazon-music';
UPDATE services SET aliases = ARRAY['тайдал', 'tidal hifi'] WHERE slug = 'tidal';
UPDATE services SET aliases = ARRAY['дизер', 'deezer premium'] WHERE slug = 'deezer';
UPDATE services SET aliases = ARRAY['soundcloud go', 'саундклауд', 'soundcloud go+'] WHERE slug = 'soundcloud';
UPDATE services SET aliases = ARRAY['pandora plus', 'pandora premium', 'пандора'] WHERE slug = 'pandora';
UPDATE services SET aliases = ARRAY['qobuz sublime', 'кобуз'] WHERE slug = 'qobuz';
UPDATE services SET aliases = ARRAY['idagio.com', 'идажио'] WHERE slug = 'idagio';
UPDATE services SET aliases = ARRAY['yandex music', 'яндекс музыка', 'ya music', 'yamusic'] WHERE slug = 'yandex-music';
UPDATE services SET aliases = ARRAY['vk music', 'вк музыка', 'boom', 'vk boom', 'бум'] WHERE slug = 'vk-music';
UPDATE services SET aliases = ARRAY['zvooq', 'zvuk', 'звук', 'zvuk.com'] WHERE slug = 'zvuk';
UPDATE services SET aliases = ARRAY['sber zvuk', 'сбер звук', 'сберзвук'] WHERE slug = 'sberzvuk';
UPDATE services SET aliases = ARRAY['game pass', 'xbox gamepass', 'pc game pass', 'xbox', 'xbox live', 'xbox live gold', 'gamepass', 'геймпас'] WHERE slug = 'xbox-game-pass';
UPDATE services SET aliases = ARRAY['playstation plus', 'ps plus', 'ps+', 'psn plus', 'ps extra', 'ps premium', 'ps plus extra', 'пс плюс', 'psn', 'sony playstation'] WHERE slug = 'playstation';
UPDATE services SET aliases = ARRAY['nintendo online', 'nso', 'switch online', 'nintendo', 'нинтендо'] WHERE slug = 'nintendo-switch-online';
UPDATE services SET aliases = ARRAY['ea play pro', 'origin access', 'ea app', 'origin', 'ea play', 'electronic arts', 'иа плей'] WHERE slug = 'ea-play';
UPDATE services SET aliases = ARRAY['ubisoft plus', 'ubi plus', 'ubisoft', 'ubisoft+', 'ubisoft connect', 'юбисофт'] WHERE slug = 'ubisoft-plus';
UPDATE services SET aliases = ARRAY['gfn', 'nvidia geforce now', 'geforce now', 'гефорс нау'] WHERE slug = 'geforce-now';
UPDATE services SET aliases = ARRAY['бустероид', 'boosteroid cloud'] WHERE slug = 'boosteroid';
UPDATE services SET aliases = ARRAY['shadow pc', 'shadow', 'shadow.tech', 'шадоу пк'] WHERE slug = 'shadow-pc';
UPDATE services SET aliases = ARRAY['discord nitro', 'nitro', 'дискорд', 'дискорд нитро'] WHERE slug = 'discord';
UPDATE services SET aliases = ARRAY['steam wallet', 'стим', 'steam.com'] WHERE slug = 'steam';
UPDATE services SET aliases = ARRAY['arcade', 'эпл аркада', 'applearcade'] WHERE slug = 'apple-arcade';
UPDATE services SET aliases = ARRAY['play pass', 'google play pass', 'гугл плей пасс'] WHERE slug = 'google-play-pass';
UPDATE services SET aliases = ARRAY['world of warcraft', 'wow token', 'вов', 'warcraft'] WHERE slug = 'wow';
UPDATE services SET aliases = ARRAY['ff14', 'ffxiv', 'final fantasy 14', 'final fantasy xiv', 'фф14'] WHERE slug = 'ffxiv';
UPDATE services SET aliases = ARRAY['eso plus', 'elder scrolls online', 'эсо'] WHERE slug = 'eso';
UPDATE services SET aliases = ARRAY['lostark', 'лост арк', 'lost ark'] WHERE slug = 'lost-ark';
UPDATE services SET aliases = ARRAY['poe', 'poe plus', 'путь изгнания'] WHERE slug = 'path-of-exile';
UPDATE services SET aliases = ARRAY['genshin', 'геншин', 'геншин импакт'] WHERE slug = 'genshin-impact';
UPDATE services SET aliases = ARRAY['hsr', 'star rail', 'хонкай', 'хонкай стар рейл'] WHERE slug = 'honkai-star-rail';
UPDATE services SET aliases = ARRAY['league of legends', 'lol', 'valorant', 'riot points', 'riot games', 'лига легенд'] WHERE slug = 'riot';
UPDATE services SET aliases = ARRAY['minecraft realms', 'realms', 'майнкрафт'] WHERE slug = 'minecraft';
UPDATE services SET aliases = ARRAY['роблокс', 'roblox premium'] WHERE slug = 'roblox';
UPDATE services SET aliases = ARRAY['вк плей', 'my.games', 'vkplay', 'vk play'] WHERE slug = 'vk-play';
UPDATE services SET aliases = ARRAY['мир танков', 'world of tanks', 'wows', 'леста'] WHERE slug = 'lesta';
UPDATE services SET aliases = ARRAY['icloud+', 'icloud plus', 'айклауд', 'icloud storage'] WHERE slug = 'icloud';
UPDATE services SET aliases = ARRAY['google one', 'google storage', 'гугл ван', 'google drive', 'гугл диск', 'гугл one'] WHERE slug = 'google-one';
UPDATE services SET aliases = ARRAY['дропбокс', 'dropbox plus', 'dropbox professional'] WHERE slug = 'dropbox';
UPDATE services SET aliases = ARRAY['one drive', 'microsoft onedrive', 'вандрайв'] WHERE slug = 'onedrive';
UPDATE services SET aliases = ARRAY['box.com', 'box cloud'] WHERE slug = 'box';
UPDATE services SET aliases = ARRAY['p cloud', 'пикloud', 'пиклауд'] WHERE slug = 'pcloud';
UPDATE services SET aliases = ARRAY['mega.nz', 'мега диск'] WHERE slug = 'mega';
UPDATE services SET aliases = ARRAY['back blaze', 'бэкблейз'] WHERE slug = 'backblaze';
UPDATE services SET aliases = ARRAY['i drive', 'айдрайв'] WHERE slug = 'idrive';
UPDATE services SET aliases = ARRAY['sync.com', 'sync com'] WHERE slug = 'sync-com';
UPDATE services SET aliases = ARRAY['yandex disk', 'яндекс диск', 'ya disk', 'yadisk'] WHERE slug = 'yandex-disk';
UPDATE services SET aliases = ARRAY['mail.ru cloud', 'облако mail', 'mail cloud', 'облако мейл'] WHERE slug = 'mailru-cloud';
UPDATE services SET aliases = ARRAY['proton drive', 'протон драйв'] WHERE slug = 'proton-drive';
UPDATE services SET aliases = ARRAY['office 365', 'microsoft office', 'office', 'майкрософт 365', 'ms 365', 'офис 365', 'onedrive 365'] WHERE slug = 'microsoft-365';
UPDATE services SET aliases = ARRAY['g suite', 'gsuite', 'google workspace', 'google business', 'гугл воркспейс'] WHERE slug = 'google-workspace';
UPDATE services SET aliases = ARRAY['notion ai', 'ноушен', 'notion plus', 'notion.so'] WHERE slug = 'notion';
UPDATE services SET aliases = ARRAY['слак', 'slack pro', 'slack business'] WHERE slug = 'slack';
UPDATE services SET aliases = ARRAY['zoom pro', 'зум', 'zoom workplace', 'zoom one'] WHERE slug = 'zoom';
UPDATE services SET aliases = ARRAY['эверноут', 'evernote personal'] WHERE slug = 'evernote';
UPDATE services SET aliases = ARRAY['todoist pro', 'todoist business', 'тудуист'] WHERE slug = 'todoist';
UPDATE services SET aliases = ARRAY['tick tick', 'тик тик'] WHERE slug = 'ticktick';
UPDATE services SET aliases = ARRAY['things 3', 'things3'] WHERE slug = 'things';
UPDATE services SET aliases = ARRAY['obsidian sync', 'obsidian publish', 'обсидиан'] WHERE slug = 'obsidian';
UPDATE services SET aliases = ARRAY['1 password', 'onepassword', '1password families', 'one password', 'ван пассворд'] WHERE slug = '1password';
UPDATE services SET aliases = ARRAY['last pass', 'lastpass families', 'ластпасс'] WHERE slug = 'lastpass';
UPDATE services SET aliases = ARRAY['битварден', 'bitwarden premium', 'bitwarden family'] WHERE slug = 'bitwarden';
UPDATE services SET aliases = ARRAY['dash lane', 'дэшлейн'] WHERE slug = 'dashlane';
UPDATE services SET aliases = ARRAY['keeper security', 'кипер'] WHERE slug = 'keeper';
UPDATE services SET aliases = ARRAY['adobe', 'creative cloud', 'photoshop', 'adobe cc', 'адоб', 'lightroom', 'adobe creative cloud'] WHERE slug = 'adobe-cc';
UPDATE services SET aliases = ARRAY['canva pro', 'канва', 'canva teams'] WHERE slug = 'canva';
UPDATE services SET aliases = ARRAY['figma professional', 'фигма', 'figma organization'] WHERE slug = 'figma';
UPDATE services SET aliases = ARRAY['миро', 'miro starter', 'miro business'] WHERE slug = 'miro';
UPDATE services SET aliases = ARRAY['openai', 'chatgpt plus', 'chatgpt pro', 'чатгпт', 'chat gpt', 'чат gpt', 'чатgpt'] WHERE slug = 'chatgpt';
UPDATE services SET aliases = ARRAY['anthropic', 'claude pro', 'claude max', 'клод', 'claude ai', 'anthropic claude'] WHERE slug = 'claude';
UPDATE services SET aliases = ARRAY['google gemini', 'gemini advanced', 'gemini pro', 'bard', 'google ai', 'google ai pro', 'google one ai', 'google ai premium', 'google ai ultra'] WHERE slug = 'gemini';
UPDATE services SET aliases = ARRAY['perplexity pro', 'перплексити', 'perplexity ai'] WHERE slug = 'perplexity';
UPDATE services SET aliases = ARRAY['copilot', 'github copilot', 'копилот', 'copilot pro'] WHERE slug = 'github-copilot';
UPDATE services SET aliases = ARRAY['cursor pro', 'cursor ai', 'курсор'] WHERE slug = 'cursor';
UPDATE services SET aliases = ARRAY['миджорни', 'mid journey'] WHERE slug = 'midjourney';
UPDATE services SET aliases = ARRAY['runway ml', 'runway gen', 'ранвей'] WHERE slug = 'runway';
UPDATE services SET aliases = ARRAY['eleven labs', 'илевенлабс'] WHERE slug = 'elevenlabs';
UPDATE services SET aliases = ARRAY['граммарли', 'grammarly premium'] WHERE slug = 'grammarly';
UPDATE services SET aliases = ARRAY['superhuman mail', 'суперхуман'] WHERE slug = 'superhuman';
UPDATE services SET aliases = ARRAY['linear app', 'linear team', 'линейр'] WHERE slug = 'linear';
UPDATE services SET aliases = ARRAY['atlassian jira', 'джира', 'atlassian'] WHERE slug = 'jira';
UPDATE services SET aliases = ARRAY['atlassian confluence', 'конфлюенс'] WHERE slug = 'confluence';
UPDATE services SET aliases = ARRAY['трелло', 'trello premium'] WHERE slug = 'trello';
UPDATE services SET aliases = ARRAY['асана', 'asana premium'] WHERE slug = 'asana';
UPDATE services SET aliases = ARRAY['monday', 'мандей', 'monday.com', 'monday com', 'monday work'] WHERE slug = 'monday';
UPDATE services SET aliases = ARRAY['click up', 'кликап'] WHERE slug = 'clickup';
UPDATE services SET aliases = ARRAY['air table', 'эйртейбл'] WHERE slug = 'airtable';
UPDATE services SET aliases = ARRAY['set app', 'сетапп'] WHERE slug = 'setapp';
UPDATE services SET aliases = ARRAY['web flow', 'вебфлоу'] WHERE slug = 'webflow';
UPDATE services SET aliases = ARRAY['mail chimp', 'мейлчимп'] WHERE slug = 'mailchimp';
UPDATE services SET aliases = ARRAY['kit', 'convert kit', 'конверткит'] WHERE slug = 'convertkit';
UPDATE services SET aliases = ARRAY['hub spot', 'хабспот'] WHERE slug = 'hubspot';
UPDATE services SET aliases = ARRAY['sales force', 'сейлсфорс'] WHERE slug = 'salesforce';
UPDATE services SET aliases = ARRAY['cron calendar', 'notion calendar', 'ноушен календарь'] WHERE slug = 'notion-calendar';
UPDATE services SET aliases = ARRAY['calendarly', 'календли'] WHERE slug = 'calendly';
UPDATE services SET aliases = ARRAY['loom video', 'лум'] WHERE slug = 'loom';
UPDATE services SET aliases = ARRAY['hellosign', 'hello sign', 'дропбокс сайн'] WHERE slug = 'dropbox-sign';
UPDATE services SET aliases = ARRAY['docu sign', 'докусайн'] WHERE slug = 'docusign';
UPDATE services SET aliases = ARRAY['quick books', 'квикбукс'] WHERE slug = 'quickbooks';
UPDATE services SET aliases = ARRAY['fresh books', 'фрешбукс'] WHERE slug = 'freshbooks';
UPDATE services SET aliases = ARRAY['toggl', 'toggl track', 'тоггл'] WHERE slug = 'toggl';
UPDATE services SET aliases = ARRAY['rescuetime', 'rescue time'] WHERE slug = 'rescue-time';
UPDATE services SET aliases = ARRAY['raindrop', 'raindrop.io', 'рейндроп'] WHERE slug = 'raindrop';
UPDATE services SET aliases = ARRAY['reader readwise', 'readwise reader', 'ридуайз'] WHERE slug = 'readwise';
UPDATE services SET aliases = ARRAY['getpocket', 'pocket premium', 'покет'] WHERE slug = 'pocket';
UPDATE services SET aliases = ARRAY['protonmail', 'proton mail', 'протон почта', 'proton'] WHERE slug = 'proton-mail';
UPDATE services SET aliases = ARRAY['fast mail', 'фастмейл'] WHERE slug = 'fastmail';
UPDATE services SET aliases = ARRAY['hey.com', 'hey email', 'hey mail'] WHERE slug = 'hey-email';
UPDATE services SET aliases = ARRAY['nord vpn', 'nordvpn', 'нордвпн'] WHERE slug = 'nordvpn';
UPDATE services SET aliases = ARRAY['express vpn', 'экспрессвпн'] WHERE slug = 'expressvpn';
UPDATE services SET aliases = ARRAY['surf shark', 'серфшарк'] WHERE slug = 'surfshark';
UPDATE services SET aliases = ARRAY['protonvpn', 'proton vpn', 'протон впн'] WHERE slug = 'proton-vpn';
UPDATE services SET aliases = ARRAY['mullvad vpn', 'малльвад'] WHERE slug = 'mullvad';
UPDATE services SET aliases = ARRAY['cyber ghost', 'кибергост'] WHERE slug = 'cyberghost';
UPDATE services SET aliases = ARRAY['pia vpn', 'private internet access'] WHERE slug = 'pia';
UPDATE services SET aliases = ARRAY['adguard vpn', 'адгард', 'ad guard'] WHERE slug = 'adguard';
UPDATE services SET aliases = ARRAY['next dns', 'некстднс'] WHERE slug = 'nextdns';
UPDATE services SET aliases = ARRAY['cloudflare', 'cloudflare warp', '1.1.1.1', 'клаудфлейр'] WHERE slug = 'cloudflare-zero-trust';
UPDATE services SET aliases = ARRAY['vercel.com', 'версель'] WHERE slug = 'vercel';
UPDATE services SET aliases = ARRAY['netlify.com', 'нетлифай'] WHERE slug = 'netlify';
UPDATE services SET aliases = ARRAY['digital ocean', 'do droplets', 'диджитал океан'] WHERE slug = 'digitalocean';
UPDATE services SET aliases = ARRAY['akamai linode', 'akamai cloud', 'линод'] WHERE slug = 'linode';
UPDATE services SET aliases = ARRAY['hetzner cloud', 'хетцнер'] WHERE slug = 'hetzner';
UPDATE services SET aliases = ARRAY['aws', 'amazon aws', 'amazon web services', 'амазон aws'] WHERE slug = 'aws';
UPDATE services SET aliases = ARRAY['github pro', 'github team', 'гитхаб', 'git hub'] WHERE slug = 'github';
UPDATE services SET aliases = ARRAY['gitlab.com', 'гитлаб'] WHERE slug = 'gitlab';
UPDATE services SET aliases = ARRAY['namecheap', 'name cheap', 'неймчип'] WHERE slug = 'domain-registrar';
UPDATE services SET aliases = ARRAY['go daddy', 'годедди'] WHERE slug = 'godaddy';
UPDATE services SET aliases = ARRAY['cloudflare registrar', 'cloudflare domains'] WHERE slug = 'cloudflare-registrar';
UPDATE services SET aliases = ARRAY['telegram premium', 'телеграм', 'телеграм премиум', 'tg premium', 'телега', 'tg'] WHERE slug = 'telegram';
UPDATE services SET aliases = ARRAY['whatsapp plus', 'ватсап', 'whats app', 'вацап'] WHERE slug = 'whatsapp';
UPDATE services SET aliases = ARRAY['twitter', 'twitter blue', 'x.com', 'x premium', 'twitter premium', 'твиттер'] WHERE slug = 'x';
UPDATE services SET aliases = ARRAY['linkedin premium', 'линкедин', 'linked in'] WHERE slug = 'linkedin';
UPDATE services SET aliases = ARRAY['reddit premium', 'reddit gold', 'реддит'] WHERE slug = 'reddit';
UPDATE services SET aliases = ARRAY['sber prime', 'сбер прайм', 'sberprime', 'сберпрайм', 'сбербанк прайм', 'sber', 'сбер', 'сбербанк'] WHERE slug = 'sberprime';
UPDATE services SET aliases = ARRAY['tinkoff', 'тинькофф', 't-pro', 'tinkoff pro', 'тинькофф про', 'т-про', 'tbank', 'tbank pro', 't-bank', 't bank', 'т-банк', 'т банк', 'тбанк', 'тинькоф', 'tinkoff black', 'tinkoff premium', 'т банк про'] WHERE slug = 'tinkoff';
UPDATE services SET aliases = ARRAY['mts', 'mts premium', 'мтс премиум', 'мтс', 'mts music'] WHERE slug = 'mts';
UPDATE services SET aliases = ARRAY['megafon', 'мегафон', 'mega fon'] WHERE slug = 'megafon';
UPDATE services SET aliases = ARRAY['beeline', 'билайн подписка', 'билайн', 'beeline подписка'] WHERE slug = 'beeline';
UPDATE services SET aliases = ARRAY['vk combo', 'вк', 'вк комбо', 'vk подписка', 'vkontakte', 'вконтакте', 'вк музыка', 'vk'] WHERE slug = 'vk';
UPDATE services SET aliases = ARRAY['ok', 'ok vip', 'одноклассники', 'одноклассники vip', 'ok.ru', 'однокласы'] WHERE slug = 'ok';
UPDATE services SET aliases = ARRAY['strava summit', 'страва'] WHERE slug = 'strava';
UPDATE services SET aliases = ARRAY['peloton app', 'пелотон'] WHERE slug = 'peloton';
UPDATE services SET aliases = ARRAY['nike run club', 'ntc', 'nrc', 'nike training', 'найк'] WHERE slug = 'nike-training';
UPDATE services SET aliases = ARRAY['fitbit premium', 'фитбит'] WHERE slug = 'fitbit';
UPDATE services SET aliases = ARRAY['my fitness pal', 'майфитнес'] WHERE slug = 'myfitnesspal';
UPDATE services SET aliases = ARRAY['хедспейс', 'headspace plus'] WHERE slug = 'headspace';
UPDATE services SET aliases = ARRAY['калм', 'calm premium'] WHERE slug = 'calm';
UPDATE services SET aliases = ARRAY['better help', 'беттерхелп'] WHERE slug = 'betterhelp';
UPDATE services SET aliases = ARRAY['whoop membership', 'вуп'] WHERE slug = 'whoop';
UPDATE services SET aliases = ARRAY['garmin connect', 'garmin connect+', 'garmin connect plus', 'гармин'] WHERE slug = 'garmin';
UPDATE services SET aliases = ARRAY['freeletics coach', 'фрилетикс'] WHERE slug = 'freeletics';
UPDATE services SET aliases = ARRAY['future.co', 'future fitness', 'фьючер фитнес'] WHERE slug = 'future-fitness';
UPDATE services SET aliases = ARRAY['downdog yoga', 'down dog', 'даун дог'] WHERE slug = 'down-dog';
UPDATE services SET aliases = ARRAY['7min', '7 minute workout', 'seven workout'] WHERE slug = 'seven-workouts';
UPDATE services SET aliases = ARRAY['apple fitness', 'apple fitness plus', 'fitness+', 'apple fitness+', 'эпл фитнес'] WHERE slug = 'apple-fitness-plus';
UPDATE services SET aliases = ARRAY['new york times', 'nytimes', 'nyt', 'ny times', 'нью йорк таймс'] WHERE slug = 'nyt';
UPDATE services SET aliases = ARRAY['wall street journal', 'wsj', 'wall street', 'волл стрит'] WHERE slug = 'wsj';
UPDATE services SET aliases = ARRAY['wapo', 'washington post', 'washingtonpost', 'вашингтон пост'] WHERE slug = 'washington-post';
UPDATE services SET aliases = ARRAY['athletic', 'зе атлетик'] WHERE slug = 'the-athletic';
UPDATE services SET aliases = ARRAY['economist', 'the economist', 'экономист'] WHERE slug = 'economist';
UPDATE services SET aliases = ARRAY['bloomberg.com', 'блумберг'] WHERE slug = 'bloomberg';
UPDATE services SET aliases = ARRAY['financial times', 'ft.com', 'файнэншл таймс'] WHERE slug = 'ft';
UPDATE services SET aliases = ARRAY['wired.com', 'вайред'] WHERE slug = 'wired';
UPDATE services SET aliases = ARRAY['medium membership', 'медиум'] WHERE slug = 'medium';
UPDATE services SET aliases = ARRAY['сабстек', 'sub stack'] WHERE slug = 'substack';
UPDATE services SET aliases = ARRAY['медуза', 'meduza.io'] WHERE slug = 'meduza';
UPDATE services SET aliases = ARRAY['форбс', 'forbes.com'] WHERE slug = 'forbes';
UPDATE services SET aliases = ARRAY['rbc', 'рбк pro', 'рбк', 'rbc.ru'] WHERE slug = 'rbc';
UPDATE services SET aliases = ARRAY['vedomosti', 'ведомости', 'vedomosti.ru'] WHERE slug = 'vedomosti';
UPDATE services SET aliases = ARRAY['kommersant', 'коммерсант', 'коммерсантъ', 'kommersant.ru'] WHERE slug = 'kommersant';
UPDATE services SET aliases = ARRAY['thebell', 'зе белл'] WHERE slug = 'the-bell';
UPDATE services SET aliases = ARRAY['duolingo super', 'дуолинго', 'duolingo max', 'duolingo plus'] WHERE slug = 'duolingo';
UPDATE services SET aliases = ARRAY['coursera plus', 'курсера'] WHERE slug = 'coursera';
UPDATE services SET aliases = ARRAY['skill share', 'скиллшер'] WHERE slug = 'skillshare';
UPDATE services SET aliases = ARRAY['master class', 'мастеркласс'] WHERE slug = 'masterclass';
UPDATE services SET aliases = ARRAY['lynda', 'linkedin learning', 'линкедин лернинг'] WHERE slug = 'linkedin-learning';
UPDATE services SET aliases = ARRAY['brilliant.org', 'бриллиант'] WHERE slug = 'brilliant';
UPDATE services SET aliases = ARRAY['баббель', 'babel'] WHERE slug = 'babbel';
UPDATE services SET aliases = ARRAY['бусу', 'busuu.com'] WHERE slug = 'busuu';
UPDATE services SET aliases = ARRAY['rosetta stone', 'розетта стоун'] WHERE slug = 'rosetta-stone';
UPDATE services SET aliases = ARRAY['chess.com', 'chesscom', 'chess', 'чесс'] WHERE slug = 'chess-com';
UPDATE services SET aliases = ARRAY['lichess.org', 'личесс'] WHERE slug = 'lichess';
UPDATE services SET aliases = ARRAY['юдеми', 'udemy pro', 'udemy personal'] WHERE slug = 'udemy';
UPDATE services SET aliases = ARRAY['юдасити', 'udacity.com'] WHERE slug = 'udacity';
UPDATE services SET aliases = ARRAY['data camp', 'датакемп'] WHERE slug = 'datacamp';
UPDATE services SET aliases = ARRAY['code academy', 'codecademy pro', 'кодакадеми'] WHERE slug = 'codecademy';
UPDATE services SET aliases = ARRAY['plural sight', 'плюралсайт'] WHERE slug = 'pluralsight';
UPDATE services SET aliases = ARRAY['скиллбокс', 'skill box'] WHERE slug = 'skillbox';
UPDATE services SET aliases = ARRAY['netology', 'нетология', 'netology.ru'] WHERE slug = 'netology';
UPDATE services SET aliases = ARRAY['гикбрейнс', 'geek brains'] WHERE slug = 'geekbrains';
UPDATE services SET aliases = ARRAY['yandex practicum', 'практикум', 'practicum', 'яндекс практикум', 'practicum.yandex'] WHERE slug = 'practicum';
UPDATE services SET aliases = ARRAY['скайенг', 'sky eng'] WHERE slug = 'skyeng';
UPDATE services SET aliases = ARRAY['skysmart', 'скайсмарт', 'sky smart'] WHERE slug = 'skyeng-teachers';
UPDATE services SET aliases = ARRAY['lingualeo', 'лингвалео', 'lingua leo'] WHERE slug = 'lingualeo';
UPDATE services SET aliases = ARRAY['puzzle english', 'пазл инглиш'] WHERE slug = 'puzzle-english';
UPDATE services SET aliases = ARRAY['khan academy', 'хан академия'] WHERE slug = 'khan-academy';
UPDATE services SET aliases = ARRAY['sber disk', 'сбер диск', 'сбердиск'] WHERE slug = 'sberdisk';
UPDATE services SET aliases = ARRAY['eshop', 'e shop', 'nintendo shop', 'нинтендо магазин'] WHERE slug = 'nintendo-eshop';
UPDATE services SET aliases = ARRAY['epic', 'epic games store', 'fortnite crew', 'эпик'] WHERE slug = 'epic-games';
UPDATE services SET aliases = ARRAY['battlenet', 'blizzard', 'баттлнет', 'blizzard entertainment'] WHERE slug = 'battle-net';
UPDATE services SET aliases = ARRAY['amazon luna', 'амазон луна'] WHERE slug = 'luna';
UPDATE services SET aliases = ARRAY['apple one', 'эппл ван', 'apple bundle', 'эпл one'] WHERE slug = 'apple-one';
UPDATE services SET aliases = ARRAY['copilot pro', 'microsoft copilot pro', 'microsoft copilot', 'майкрософт копилот'] WHERE slug = 'microsoft-copilot';
UPDATE services SET aliases = ARRAY['запиер', 'zapier.com'] WHERE slug = 'zapier';
UPDATE services SET aliases = ARRAY['integromat', 'мейк', 'make.com'] WHERE slug = 'make';
UPDATE services SET aliases = ARRAY['if ttt', 'ифттт'] WHERE slug = 'ifttt';
UPDATE services SET aliases = ARRAY['bit defender', 'битдефендер'] WHERE slug = 'bitdefender';
UPDATE services SET aliases = ARRAY['касперский', 'kaspersky plus', 'kaspersky internet'] WHERE slug = 'kaspersky';
UPDATE services SET aliases = ARRAY['norton 360', 'нортон'] WHERE slug = 'norton';
UPDATE services SET aliases = ARRAY['mc afee', 'макафи'] WHERE slug = 'mcafee';
UPDATE services SET aliases = ARRAY['avast one', 'аваст'] WHERE slug = 'avast';
UPDATE services SET aliases = ARRAY['malware bytes', 'малваребайц'] WHERE slug = 'malwarebytes';
UPDATE services SET aliases = ARRAY['anydo', 'any do', 'эниду'] WHERE slug = 'any-do';
UPDATE services SET aliases = ARRAY['flexibits', 'фантастикл'] WHERE slug = 'fantastical';
UPDATE services SET aliases = ARRAY['bear notes', 'bear.app'] WHERE slug = 'bear';
UPDATE services SET aliases = ARRAY['ulysses app', 'улисс'] WHERE slug = 'ulysses';
UPDATE services SET aliases = ARRAY['ia writer'] WHERE slug = 'ia-writer';
UPDATE services SET aliases = ARRAY['craft docs', 'craft.do'] WHERE slug = 'craft';
UPDATE services SET aliases = ARRAY['roam', 'roam research', 'роум'] WHERE slug = 'roam-research';
UPDATE services SET aliases = ARRAY['mem.ai', 'мем ай'] WHERE slug = 'mem';
UPDATE services SET aliases = ARRAY['reflect notes', 'reflect.app'] WHERE slug = 'reflect';
UPDATE services SET aliases = ARRAY['capcut pro', 'капкат'] WHERE slug = 'capcut';
UPDATE services SET aliases = ARRAY['дескрипт', 'descript.com'] WHERE slug = 'descript';
UPDATE services SET aliases = ARRAY['epidemic sound', 'эпидемик саунд'] WHERE slug = 'epidemic-sound';
UPDATE services SET aliases = ARRAY['art list', 'артлист'] WHERE slug = 'artlist';
UPDATE services SET aliases = ARRAY['envato elements', 'энвато'] WHERE slug = 'envato';
UPDATE services SET aliases = ARRAY['shutter stock', 'шаттерсток'] WHERE slug = 'shutterstock';
UPDATE services SET aliases = ARRAY['getty', 'гетти'] WHERE slug = 'getty-images';
UPDATE services SET aliases = ARRAY['unsplash+', 'unsplash plus', 'ансплэш'] WHERE slug = 'unsplash';
UPDATE services SET aliases = ARRAY['framer.com', 'фреймер'] WHERE slug = 'framer';
UPDATE services SET aliases = ARRAY['шопифай', 'shopify plus'] WHERE slug = 'shopify';
UPDATE services SET aliases = ARRAY['вб клуб', 'wb club', 'wildberries club', 'вайлдберриз', 'wb plus', 'wildberries plus', 'вб'] WHERE slug = 'wildberries';
UPDATE services SET aliases = ARRAY['ozon premium', 'озон', 'озон премиум', 'ozon.ru'] WHERE slug = 'ozon';
UPDATE services SET aliases = ARRAY['lavka', 'яндекс лавка', 'yandex lavka'] WHERE slug = 'yandex-lavka';
UPDATE services SET aliases = ARRAY['samokat', 'самокат', 'samokat.ru'] WHERE slug = 'samokat';
UPDATE services SET aliases = ARRAY['sbermarket', 'сбермаркет', 'kuper', 'купер', 'kuper.ru'] WHERE slug = 'kuper';
UPDATE services SET aliases = ARRAY['deliveryclub', 'деливери клаб', 'деливери', 'delivery club'] WHERE slug = 'delivery-club';
UPDATE services SET aliases = ARRAY['yandex eda', 'яндекс еда', 'eda yandex', 'yandex food'] WHERE slug = 'yandex-eda';
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
SELECT 1;
-- +goose StatementEnd
