-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS tracked_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),

    user_uuid VARCHAR(255) NOT NULL REFERENCES user_cores(user_uuid) ON DELETE CASCADE,

    name TEXT NOT NULL,
    price NUMERIC(10, 3) NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'USD',
    period VARCHAR(10) NOT NULL DEFAULT 'monthly',
    date_pay DATE NOT NULL,

    auto_renewal BOOLEAN NOT NULL DEFAULT TRUE,
    notification BOOLEAN NOT NULL DEFAULT FALSE,
    include_in_analytics BOOLEAN NOT NULL DEFAULT TRUE,
    note TEXT,

    CONSTRAINT chk_tracked_subscriptions_period CHECK (period IN ('monthly', 'yearly')),
    CONSTRAINT chk_tracked_subscriptions_currency CHECK (currency ~ '^[A-Z]{3}$')
);

CREATE INDEX IF NOT EXISTS idx_tracked_subscriptions_user_uuid ON tracked_subscriptions(user_uuid);
CREATE INDEX IF NOT EXISTS idx_tracked_subscriptions_date_pay ON tracked_subscriptions(date_pay);
CREATE INDEX IF NOT EXISTS idx_tracked_subscriptions_analytics ON tracked_subscriptions(user_uuid, include_in_analytics);

CREATE TABLE IF NOT EXISTS subscription_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    slug VARCHAR(64) NOT NULL,

    CONSTRAINT uq_subscription_categories_slug UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS tracked_subscription_categories (
    tracked_subscription_id BIGINT NOT NULL REFERENCES tracked_subscriptions(id) ON DELETE CASCADE,
    user_uuid VARCHAR(255) NOT NULL REFERENCES user_cores(user_uuid) ON DELETE CASCADE,
    category_id BIGINT NOT NULL REFERENCES subscription_categories(id) ON DELETE CASCADE,

    PRIMARY KEY (tracked_subscription_id, user_uuid, category_id)
);

CREATE INDEX IF NOT EXISTS idx_tracked_subscription_categories_category_id ON tracked_subscription_categories(category_id);
CREATE INDEX IF NOT EXISTS idx_tracked_subscription_categories_user_uuid ON tracked_subscription_categories(user_uuid);

INSERT INTO subscription_categories (slug) VALUES
    ('subscriptions'),
    ('music'),
    ('streaming'),
    ('gaming'),
    ('cloud'),
    ('productivity'),
    ('fitness'),
    ('news'),
    ('education'),
    ('utilities')
ON CONFLICT (slug) DO NOTHING;

CREATE OR REPLACE FUNCTION set_tracked_sub_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('UTC', now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_tracked_sub_updated_at_trigger ON tracked_subscriptions;
CREATE TRIGGER set_tracked_sub_updated_at_trigger
    BEFORE UPDATE ON tracked_subscriptions
    FOR EACH ROW
    EXECUTE FUNCTION set_tracked_sub_updated_at();

COMMENT ON TABLE tracked_subscriptions IS 'User-tracked service subscriptions (Netflix, Spotify, etc.)';
COMMENT ON COLUMN tracked_subscriptions.id IS 'Primary unique identifier of tracked subscription';
COMMENT ON COLUMN tracked_subscriptions.created_at IS 'Record creation timestamp';
COMMENT ON COLUMN tracked_subscriptions.updated_at IS 'Record last update timestamp';
COMMENT ON COLUMN tracked_subscriptions.user_uuid IS 'Owner of the tracked subscription';
COMMENT ON COLUMN tracked_subscriptions.name IS 'Subscription name (e.g. Netflix, Spotify)';
COMMENT ON COLUMN tracked_subscriptions.price IS 'Subscription price';
COMMENT ON COLUMN tracked_subscriptions.currency IS 'ISO 4217 currency code (USD, RUB, EUR)';
COMMENT ON COLUMN tracked_subscriptions.period IS 'Billing period: monthly or yearly';
COMMENT ON COLUMN tracked_subscriptions.date_pay IS 'Date of next subscription payment';
COMMENT ON COLUMN tracked_subscriptions.auto_renewal IS 'Whether the service subscription auto-renews';
COMMENT ON COLUMN tracked_subscriptions.notification IS 'Whether payment reminders are enabled';
COMMENT ON COLUMN tracked_subscriptions.include_in_analytics IS 'Whether subscription is included in spending analytics';
COMMENT ON COLUMN tracked_subscriptions.note IS 'Optional user note for the tracked subscription';

COMMENT ON TABLE subscription_categories IS 'Catalog of subscription categories (music, subscriptions, etc.)';
COMMENT ON COLUMN subscription_categories.slug IS 'Stable category key used for i18n on the client';

COMMENT ON TABLE tracked_subscription_categories IS 'Per-member categories for a tracked subscription';
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS set_tracked_sub_updated_at_trigger ON tracked_subscriptions;
DROP FUNCTION IF EXISTS set_tracked_sub_updated_at();

DROP INDEX IF EXISTS idx_tracked_subscription_categories_user_uuid;
DROP INDEX IF EXISTS idx_tracked_subscription_categories_category_id;
DROP TABLE IF EXISTS tracked_subscription_categories;
DROP TABLE IF EXISTS subscription_categories;

DROP INDEX IF EXISTS idx_tracked_subscriptions_analytics;
DROP INDEX IF EXISTS idx_tracked_subscriptions_date_pay;
DROP INDEX IF EXISTS idx_tracked_subscriptions_user_uuid;

DROP TABLE IF EXISTS tracked_subscriptions;
-- +goose StatementEnd
