-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS user_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    user_uuid VARCHAR(255) NOT NULL REFERENCES user_cores(user_uuid) ON DELETE CASCADE,

    subscription_id BIGINT NOT NULL REFERENCES subscriptions(id) ON DELETE CASCADE,
    transaction_type TEXT NOT NULL DEFAULT 'pending', -- тип: payment, pending
    amount DECIMAL(10,2) DEFAULT 0,
    currency TEXT DEFAULT 'RUB',
    description TEXT
);

CREATE INDEX IF NOT EXISTS idx_user_transactions_user_uuid ON user_transactions(user_uuid);
CREATE INDEX IF NOT EXISTS idx_user_transactions_subscription_id ON user_transactions(subscription_id);
CREATE INDEX IF NOT EXISTS idx_user_transactions_transaction_type ON user_transactions(transaction_type);
CREATE INDEX IF NOT EXISTS idx_user_transactions_user_uuid_status ON user_transactions(user_uuid, transaction_type);

-- +Triggers
CREATE OR REPLACE FUNCTION set_updated_at_user_transactions()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_updated_at_user_transactions_trigger ON user_transactions;
CREATE TRIGGER set_updated_at_user_transactions_trigger
    BEFORE UPDATE ON user_transactions
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_user_transactions();
-- +Triggers

COMMENT ON TABLE user_transactions IS 'User payment transactions linked to SaaS tariff plans';
COMMENT ON COLUMN user_transactions.id IS 'Primary key of the transaction';
COMMENT ON COLUMN user_transactions.created_at IS 'Transaction record creation timestamp (UTC)';
COMMENT ON COLUMN user_transactions.updated_at IS 'Transaction record last update timestamp (UTC)';
COMMENT ON COLUMN user_transactions.user_uuid IS 'Owner of the transaction; cascades on user deletion';
COMMENT ON COLUMN user_transactions.subscription_id IS 'Reference to the tariff plan being purchased; cascades on plan deletion';
COMMENT ON COLUMN user_transactions.transaction_type IS 'Transaction state: pending, payment, succeeded, canceled, failed';
COMMENT ON COLUMN user_transactions.amount IS 'Transaction amount in the specified currency';
COMMENT ON COLUMN user_transactions.currency IS 'ISO currency code for the transaction amount';
COMMENT ON COLUMN user_transactions.description IS 'Optional human-readable transaction description';
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP INDEX IF EXISTS idx_user_transactions_user_uuid_status;
DROP INDEX IF EXISTS idx_user_transactions_user_uuid;
DROP INDEX IF EXISTS idx_user_transactions_subscription_id;
DROP INDEX IF EXISTS idx_user_transactions_transaction_type;

DROP TRIGGER IF EXISTS set_updated_at_user_transactions_trigger ON user_transactions;
DROP FUNCTION IF EXISTS set_updated_at_user_transactions();

DROP TABLE IF EXISTS user_transactions;
-- +goose StatementEnd
