-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS tracked_subscription_share_proposals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),

    tracked_subscription_id BIGINT NOT NULL REFERENCES tracked_subscriptions(id) ON DELETE CASCADE,
    proposed_by_user_uuid VARCHAR(255) NOT NULL REFERENCES user_cores(user_uuid) ON DELETE CASCADE,
    status VARCHAR(16) NOT NULL DEFAULT 'pending',

    CONSTRAINT chk_tracked_subscription_share_proposals_status CHECK (status IN ('pending', 'applied', 'cancelled', 'rejected'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tracked_subscription_share_proposals_pending
    ON tracked_subscription_share_proposals(tracked_subscription_id)
    WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS idx_tracked_subscription_share_proposals_subscription_id
    ON tracked_subscription_share_proposals(tracked_subscription_id);

COMMENT ON TABLE tracked_subscription_share_proposals IS 'Pending share redistribution that requires consent of other members';
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP INDEX IF EXISTS idx_tracked_subscription_share_proposals_subscription_id;
DROP INDEX IF EXISTS uq_tracked_subscription_share_proposals_pending;
DROP TABLE IF EXISTS tracked_subscription_share_proposals;
-- +goose StatementEnd
