-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),

    plan_name TEXT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL DEFAULT 0,
    currency TEXT NOT NULL DEFAULT 'USD',
    duration_days INT NOT NULL DEFAULT 30,

    max_total_subscriptions INT,
    notification_subscriptions BOOLEAN NOT NULL DEFAULT FALSE,
    auto_find_subscriptions BOOLEAN NOT NULL DEFAULT FALSE,

    description JSONB,
    features JSONB,

    CONSTRAINT uq_subscriptions_plan_name UNIQUE (plan_name),
    CONSTRAINT chk_subscriptions_amount_non_negative CHECK (amount >= 0),
    CONSTRAINT chk_subscriptions_duration_days_positive CHECK (duration_days > 0),
    CONSTRAINT chk_subscriptions_max_total_subscriptions_non_negative CHECK (max_total_subscriptions IS NULL OR max_total_subscriptions >= 0)
);

CREATE INDEX IF NOT EXISTS idx_subscriptions_amount ON subscriptions(amount);
CREATE INDEX IF NOT EXISTS idx_subscriptions_paid_plans ON subscriptions(plan_name) WHERE amount > 0;

INSERT INTO subscriptions (plan_name, amount, currency, duration_days, max_total_subscriptions, notification_subscriptions, auto_find_subscriptions, description, features) VALUES ('Free', 0, 'RUB', 30, 10, FALSE, FALSE,
    '{
        "en": "Start tracking your subscriptions manually with essential reminders.",
        "ru": "Начните вручную отслеживать подписки с базовыми напоминаниями об оплате.",
        "de": "Verfolgen Sie Ihre Abonnements manuell – mit den wichtigsten Erinnerungen.",
        "es": "Controla tus suscripciones manualmente con recordatorios esenciales."
    }',
    '{
        "en": [
            "Up to 10 tracked subscriptions",
            "Manual subscription management",
            "Auto-renewal date tracking",
            "Payment date calendar",
            "Monthly spending overview"
        ],
        "ru": [
            "До 10 отслеживаемых подписок",
            "Ручное добавление и редактирование",
            "Отслеживание автопродления",
            "Календарь дат оплаты",
            "Обзор расходов за месяц"
        ],
        "de": [
            "Bis zu 10 Abonnements",
            "Manuelles Hinzufügen und Bearbeiten",
            "Automatische Verlängerungsdaten",
            "Kalender der Zahlungstermine",
            "Monatsübersicht der Ausgaben"
        ],
        "es": [
            "Hasta 10 suscripciones",
            "Gestión manual de suscripciones",
            "Seguimiento de renovación automática",
            "Calendario de fechas de pago",
            "Resumen mensual de gastos"
        ]
    }'
)
ON CONFLICT (plan_name) DO NOTHING;

INSERT INTO subscriptions (plan_name, amount, currency, duration_days, max_total_subscriptions, notification_subscriptions, auto_find_subscriptions, description, features) VALUES ('Premium', 166, 'RUB', 30, NULL, TRUE, TRUE,
    '{
        "en": "Full automation for subscription tracking, alerts, and renewal control.",
        "ru": "Полная автоматизация отслеживания подписок, уведомлений и контроля продлений.",
        "de": "Volle Automatisierung für Abonnement-Tracking, Benachrichtigungen und Verlängerungskontrolle.",
        "es": "Automatización completa del seguimiento de suscripciones, alertas y control de renovaciones."
    }',
    '{
        "en": [
            "Unlimited tracked subscriptions",
            "Automatic subscription detection",
            "Telegram reminders before payment",
            "Advanced spending analytics"
        ],
        "ru": [
            "Неограниченное число подписок",
            "Автоматический поиск подписок",
            "Telegram-напоминания перед оплатой",
            "Расширенная аналитика расходов"
        ],
        "de": [
            "Unbegrenzte Anzahl an Abonnements",
            "Automatische Abonnement-Erkennung",
            "Telegram-Erinnerungen vor der Zahlung",
            "Erweiterte Ausgabenanalyse"
        ],
        "es": [
            "Suscripciones ilimitadas",
            "Detección automática de suscripciones",
            "Recordatorios por Telegram antes del pago",
            "Análisis avanzado de gastos"
        ]
    }'
)
ON CONFLICT (plan_name) DO NOTHING;

COMMENT ON TABLE subscriptions IS 'SaaS tariff plans for Paylist subscription tracking service';
COMMENT ON COLUMN subscriptions.id IS 'Primary key of the tariff plan';
COMMENT ON COLUMN subscriptions.created_at IS 'Plan record creation timestamp (UTC)';
COMMENT ON COLUMN subscriptions.plan_name IS 'Unique plan identifier shown to users (e.g. Free, Premium)';
COMMENT ON COLUMN subscriptions.amount IS 'Plan price per billing period';
COMMENT ON COLUMN subscriptions.currency IS 'ISO currency code for the plan price';
COMMENT ON COLUMN subscriptions.duration_days IS 'Billing period length in days';
COMMENT ON COLUMN subscriptions.max_total_subscriptions IS 'Maximum tracked subscriptions per user; NULL means unlimited';
COMMENT ON COLUMN subscriptions.notification_subscriptions IS 'Whether the plan includes Telegram payment reminders';
COMMENT ON COLUMN subscriptions.auto_find_subscriptions IS 'Whether the plan includes automatic subscription detection';
COMMENT ON COLUMN subscriptions.description IS 'Localized short plan description (JSON: en, ru, de, es)';
COMMENT ON COLUMN subscriptions.features IS 'Localized list of plan features (JSON: en[], ru[], de[], es[])';

ALTER TABLE user_subscriptions
    DROP CONSTRAINT IF EXISTS fk_user_subscriptions_plan_name;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_user_subscriptions_plan_name'
    ) THEN
        ALTER TABLE user_subscriptions
            ADD CONSTRAINT fk_user_subscriptions_plan_name
            FOREIGN KEY (plan_name) REFERENCES subscriptions(plan_name)
            ON UPDATE CASCADE
            ON DELETE RESTRICT;
    END IF;
END $$;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
ALTER TABLE user_subscriptions
    DROP CONSTRAINT IF EXISTS fk_user_subscriptions_plan_name;

DROP TRIGGER IF EXISTS set_updated_at_subscriptions_trigger ON subscriptions;
DROP FUNCTION IF EXISTS set_updated_at_subscriptions();

DROP INDEX IF EXISTS idx_subscriptions_paid_plans;
DROP INDEX IF EXISTS idx_subscriptions_amount;

DROP TABLE IF EXISTS subscriptions;
-- +goose StatementEnd
