upstream api {
    zone api_zone 64k;
    least_conn;

    server 127.0.0.1:8080;

    # server 127.0.0.1:8181 max_fails=3 fail_timeout=30s;
}

server {
    listen 80;
    server_name paylist.site;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name paylist.site;

    root /usr/share/nginx/html/paylist;
    index index.html;

    # --- SSL настройки ---
    ssl_certificate /etc/letsencrypt/live/paylist.site/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/paylist.site/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
    #ssl_protocols TLSv1.2 TLSv1.3;
    #ssl_prefer_server_ciphers on;
    #ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384';

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header X-XSS-Protection "1; mode=block";
    add_header Referrer-Policy "strict-origin-when-cross-origin";

    access_log /var/log/nginx/paylist.access.log;
    error_log /var/log/nginx/paylist.error.log;

    location / {
        try_files $uri $uri/ /index.html =404;

        if ($http_user_agent ~* "(?:wget|curl|python-requests)") {
            return 403;
        }
    }

    location /api/v1/ {
        client_max_body_size 8m;
	    proxy_pass http://api;
	    proxy_next_upstream error timeout invalid_header http_500 http_502 http_504;
        proxy_http_version 1.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location = /c-r-web/_runtime_config.js {
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }

    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }

    location ~* \.(jpg|jpeg|png|gif|ico)$ {
        expires 10d;
        add_header Cache-Control "public";
    }

    location ~* \.(conf|yaml|ini)$ {
        deny all;
        access_log off;
        log_not_found off;
    }

    #include /etc/nginx/extra-conf.d/*.conf;
}
