#!/bin/bash

sudo apt update && sudo apt install -y git

#install golang

sudo apt install -y postgresql postgresql-contrib
sudo systemctl status postgresql

sudo apt install -y make python3 python3-venv python3-pip

go install github.com/pressly/goose/v3/cmd/goose@latest

echo 'export PATH=$PATH:/root/go/bin' >> ~/.bashrc
source ~/.bashrc
